baseurl             = "https://linderud.dev/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "nb"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Morten Linderud"
title               = "Morten Linderud"
pygmentsuseclasses  = true
#pluralizelisttitles = false
highlightjs = true

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Tags"
weight                 = -110
identifier             = "tags"
url                    = "/tags/"

#[[menu.main]]
#name                   = "Code"
#weight                 = -100
#identifier             = "code"
#url                    = "/code/"

[params]
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Morten Linderud"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Meandring through cyberspace"
email                  = "morten@linderud.pw"
lang                   = "en"
selfintro              = "F/OSS Developer, Arch Linux Developer and security team."
github                 = "//github.com/Foxboron"
twitter                = "//twitter.com/MortenLinderud"
mastodon               = "//chaos.social/@Foxboron"
avatar = "img/profile.png"

[taxonomies]
  tag = "tags"
